#!/usr/bin/env python3
"""Generate APS Rust entry points + implementation metadata from Gherkin IR.

Usage:
    APS_FEATURE_PATH=/abs/working-copy/feature.feature \
        acceptance_entrypoint_generator.py <json-ir> <generated-dir>

The IR is the `bb gherkin-parser` output:
    {"name": ..., "scenarios": [{"name", "steps": [{"keyword", "text"}],
                                 "examples": [{"col": "value"}]}]}

Writes (atomically):
    <generated-dir>/entry_points.rs   one #[test] per scenario execution,
                                      calling crate::runtime::run_execution
                                      (scenario and example indexes are
                                      1-based; example index 0 is used for
                                      scenarios without an Examples table)
    <generated-dir>/metadata/<slug>.json
                                      implementation-hash bookkeeping read
                                      by the APS mutator; `feature_path`
                                      must be the ABSOLUTE path of the
                                      working copy (= --feature).

The slug mirrors the Clojure `feature-metadata-slug` of the APS mutator
(lowercase, [a-z0-9] kept, every other character folded to one hyphen,
leading/trailing hyphens trimmed) plus ".json".

Exit codes: 0 ok, 1 usage error (missing APS_FEATURE_PATH), 2 invalid IR.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import tempfile
from pathlib import Path


def rust_ident(name: str) -> str:
    chars = []
    for ch in name.lower():
        chars.append(ch if ch.isascii() and ch.isalnum() else "_")
    ident = re.sub(r"_+", "_", "".join(chars)).strip("_")
    if not ident:
        ident = "scenario"
    if ident[0].isdigit():
        ident = "s" + ident
    return ident


def feature_slug(feature_path: str) -> str:
    slug = "".join(ch if ch.isascii() and ch.isalnum() else "-" for ch in feature_path.lower())
    return re.sub(r"-+", "-", slug).strip("-")


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1
    feature_path = os.environ.get("APS_FEATURE_PATH", "").strip()
    if not feature_path or not os.path.isabs(feature_path):
        print(
            "acceptance_entrypoint_generator: APS_FEATURE_PATH must be set to the "
            "absolute path of the working feature copy",
            file=sys.stderr,
        )
        return 1
    ir_path = Path(argv[1])
    generated_dir = Path(argv[2])
    try:
        ir = json.loads(ir_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as err:
        print(f"acceptance_entrypoint_generator: unreadable IR {ir_path}: {err}", file=sys.stderr)
        return 2
    feature_name = ir.get("name")
    scenarios = ir.get("scenarios")
    if not isinstance(feature_name, str) or not isinstance(scenarios, list):
        print("acceptance_entrypoint_generator: IR must carry name + scenarios", file=sys.stderr)
        return 2

    tests: list[str] = []
    total = 0
    for scenario_index, scenario in enumerate(scenarios, start=1):
        name = scenario.get("name", f"scenario_{scenario_index}")
        examples = scenario.get("examples") or []
        count = len(examples) if examples else 1
        for example_index in range(1, count + 1):
            idx = example_index if examples else 0
            total += 1
            ident = f"scenario_{scenario_index}_{rust_ident(name)}_example_{idx}"
            tests.append(f"#[test]\nfn {ident}() {{\n    crate::runtime::run_execution({scenario_index}, {idx});\n}}\n")
    body = (
        "// GENERATED by src-tauri/tools/acceptance_entrypoint_generator.py — DO NOT EDIT.\n"
        f"// Feature: {feature_name}\n"
        f"// Source:  {feature_path}\n"
        f"// Executions: {total}\n\n"
        + "\n".join(tests)
    )
    implementation_hash = "sha256:" + hashlib.sha256(body.encode("utf-8")).hexdigest()
    atomic_write(generated_dir / "entry_points.rs", body)
    metadata = {
        "schema_version": 1,
        "feature_path": feature_path,
        "ir_path": str(ir_path),
        "implementation_hash": implementation_hash,
        "hash_scope": "generated_files",
        "generated_files": ["entry_points.rs"],
    }
    slug_file = generated_dir / "metadata" / (feature_slug(feature_path) + ".json")
    atomic_write(slug_file, json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    print(f"acceptance_entrypoint_generator: {total} execution(s) -> {generated_dir / 'entry_points.rs'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
