//! STRUCTURAL application services (schema v3): mutate the story's node
//! graph — add / delete / move a node, add / link / remove an option.
//!
//! Sibling of the node-content services (`node.rs`) with the SAME
//! transactional spine: `BEGIN IMMEDIATE`, the fail-closed `story_edit_scope`
//! guard, refusal on persisted BLOCKING facts, whole-graph mutation,
//! re-serialization + per-write checksum recompute, a post-mutation
//! `has_blocking` defense, one UPDATE, commit (NFR9 / FR18). Differences by
//! design: the mutation closure receives the WHOLE `CanonicalStructure` (not
//! one node), and the node draft is NEVER consumed here (the draft protects
//! CONTENT; the frontend flushes pending content BEFORE any structural
//! mutation — deleting a node purges ITS draft only, conditionally).
//!
//! A structural write may legitimately LEAVE a Fixable `BrokenOptionLink`
//! behind (deleting a referenced node keeps the pointing options, flagged
//! `destination à corriger`) — the post-mutation defense therefore rejects
//! BLOCKING blockers only, mirroring the node path.

use rusqlite::{OptionalExtension, Transaction};

use crate::application::story::node::MAX_NODE_LABEL_CHARS;
use crate::application::story::now_iso_ms;
use crate::application::story::scope::{story_edit_scope, StoryEditScope};
use crate::domain::shared::AppError;
use crate::domain::story::{
    canonical_structure_json, content_checksum, validate_canonical, CanonicalNode, CanonicalOption,
    CanonicalStoryFacts, CanonicalStructure, Severity,
};
use crate::infrastructure::db::DbHandle;
use crate::ipc::dto::{NodeGraphDto, OptionLinkDto, StoryStructureDto, StructureWriteOutputDto};
use std::collections::HashSet;
use std::path::Path;

/// Direction of a node move in the DISPLAY order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MoveDirection {
    Up,
    Down,
}

// ---------------------------------------------------------------------------
// Projection (read side) — shared with `get_story_detail`
// ---------------------------------------------------------------------------

/// Project the node graph into its LIGHT wire DTO for the navigator. Pure —
/// no DB, no filesystem. Derives, in Rust only, each option's link `state`
/// (`unlinked` / `linked` / `broken`) and each node's localized `has_issue`
/// flag (at least one broken option link).
pub fn project_structure(structure: &CanonicalStructure) -> StoryStructureDto {
    let ids: HashSet<&str> = structure.nodes.iter().map(|n| n.id.as_str()).collect();
    StoryStructureDto {
        start_node_id: structure.start_node_id.clone(),
        nodes: structure
            .nodes
            .iter()
            .map(|node| {
                let options: Vec<OptionLinkDto> = node
                    .options
                    .iter()
                    .map(|option| OptionLinkDto {
                        label: option.label.clone(),
                        target: option.target.clone(),
                        state: match option.target.as_deref() {
                            None => "unlinked",
                            Some(target) if ids.contains(target) => "linked",
                            Some(_) => "broken",
                        }
                        .to_string(),
                    })
                    .collect();
                NodeGraphDto {
                    id: node.id.clone(),
                    label: node.label.clone(),
                    is_start: node.id == structure.start_node_id,
                    has_issue: options.iter().any(|o| o.state == "broken"),
                    options,
                }
            })
            .collect(),
    }
}

/// The smallest free `n<k>` id (n1, n2, …) — deterministic and generated by
/// Rust only, never by the frontend. Uniqueness is then re-guarded by the
/// graph validation (`DuplicateNodeId`).
///
/// "Free" reserves BOTH the existing node ids AND every `option.target` —
/// including targets whose node was deleted (a `destination à corriger`
/// trace). Recycling such an id would silently transmute a flagged broken
/// link into a live link toward an unrelated new node.
fn next_free_node_id(structure: &CanonicalStructure) -> String {
    let reserved: HashSet<&str> = structure
        .nodes
        .iter()
        .map(|n| n.id.as_str())
        .chain(
            structure
                .nodes
                .iter()
                .flat_map(|n| n.options.iter())
                .filter_map(|o| o.target.as_deref()),
        )
        .collect();
    let mut k: usize = 1;
    loop {
        let candidate = format!("n{k}");
        if !reserved.contains(candidate.as_str()) {
            return candidate;
        }
        k += 1;
    }
}

// ---------------------------------------------------------------------------
// Write spine
// ---------------------------------------------------------------------------

/// Load the story's canonical structure inside a write transaction, run
/// `mutate` on the WHOLE graph, re-validate, re-serialize, recompute the
/// checksum, bump `updated_at`, and commit. Returns the structural write
/// acknowledgement (with the re-projected graph) plus whatever `mutate`
/// produced. Any early return drops the transaction, which rolls it back —
/// the previous canonical body is preserved (NFR9).
fn apply_structure_mutation<F, T>(
    db: &mut DbHandle,
    story_id: &str,
    mutate: F,
) -> Result<(StructureWriteOutputDto, T), AppError>
where
    F: FnOnce(&mut CanonicalStructure, &Transaction<'_>) -> Result<T, AppError>,
{
    let now_iso = now_iso_ms()?;
    let tx = db
        .conn_mut()
        .transaction_with_behavior(rusqlite::TransactionBehavior::Immediate)
        .map_err(|e| transport_error(&e, "begin_transaction", story_id))?;

    // Authoritative edit-scope guard (FR21, fail-closed): a structural write
    // requires the FULL scope — a device-pack story's structure is carried by
    // the copied pack (its local canonical row is a placeholder). The UI never
    // offers the controls, but a direct IPC call or a stale UI state must be
    // refused here. The derived scope is reused for the acknowledgement's
    // `importState` (same None-unless-Full rule as the detail projection).
    let scope = story_edit_scope(&tx, story_id);
    if scope != StoryEditScope::Full {
        return Err(structure_not_editable(story_id));
    }

    let row: Option<(String, u32, String, String, String)> = tx
        .query_row(
            "SELECT title, schema_version, structure_json, content_checksum, updated_at \
             FROM stories WHERE id = ?1",
            rusqlite::params![story_id],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?, r.get(3)?, r.get(4)?)),
        )
        .optional()
        .map_err(|e| transport_error(&e, "read", story_id))?;
    let (title, schema_version, structure_json, stored_checksum, stored_updated_at) = match row {
        Some(values) => values,
        None => return Err(story_missing(story_id)),
    };

    // Refuse to mutate a story whose PERSISTED canonical facts carry a
    // BLOCKING issue: a structural write must never silently "repair" an
    // on-disk corruption by overwriting it with a fresh checksum. A FIXABLE
    // issue (an invalid title, an already-broken option link) does NOT block —
    // fixing a broken link IS a structural mutation, so blocking on it would
    // deadlock the repair.
    let persisted_facts = CanonicalStoryFacts {
        title: title.clone(),
        schema_version,
        structure_json: structure_json.clone(),
        content_checksum: stored_checksum.clone(),
    };
    if has_blocking(&persisted_facts) {
        return Err(structure_corrupt(story_id));
    }

    let mut structure: CanonicalStructure =
        serde_json::from_str(&structure_json).map_err(|_| structure_corrupt(story_id))?;

    let extra = mutate(&mut structure, &tx)?;

    let new_json = canonical_structure_json(&structure);

    // A mutation that lands on the EXACT same canonical bytes (e.g. a move
    // with no room, a stale double-click) is acknowledged WITHOUT touching
    // the row: rewriting would bump `updated_at` — a persisted, exported,
    // user-visible metadata — for zero actual change. No REAL write happened,
    // so a pending import review is NOT resolved either — but the ACK still
    // carries the CURRENT state read in this transaction (it never lies).
    if new_json == structure_json {
        let projected = project_structure(&structure);
        let import_state =
            crate::application::story::review::read_import_state(&tx, story_id, scope)?;
        tx.commit()
            .map_err(|e| transport_error(&e, "commit", story_id))?;
        return Ok((
            StructureWriteOutputDto {
                id: story_id.to_string(),
                updated_at: stored_updated_at,
                content_checksum: stored_checksum,
                structure_json: new_json,
                structure: projected,
                import_state: import_state.map(|s| s.wire_tag().to_string()),
            },
            extra,
        ));
    }

    let new_checksum = content_checksum(&new_json);

    // Defense in depth: the mutated graph must not introduce a BLOCKING
    // incoherence (duplicate id, invalid start, empty graph). A Fixable
    // outcome (a link left pointing at the node just deleted) is a legitimate
    // authoring state — flagged, never refused. The COMPLETE post-mutation
    // blocker list is kept: `Blocking` refuses the write, and the full list
    // (any severity) is then the review-resolution oracle — zero extra I/O.
    let facts = CanonicalStoryFacts {
        title,
        schema_version,
        structure_json: new_json.clone(),
        content_checksum: new_checksum.clone(),
    };
    let post_mutation_blockers = validate_canonical(&facts);
    if post_mutation_blockers
        .iter()
        .any(|b| b.severity == Severity::Blocking)
    {
        return Err(structure_corrupt(story_id));
    }

    tx.execute(
        "UPDATE stories SET structure_json = ?1, content_checksum = ?2, updated_at = ?3 WHERE id = ?4",
        rusqlite::params![new_json, new_checksum, now_iso, story_id],
    )
    .map_err(|e| transport_error(&e, "update", story_id))?;

    // A real write that leaves the canonical story ENTIRELY sound settles a
    // pending import review (AC3) — inside this same transaction. The
    // acknowledgement then carries the state read POST-UPDATE.
    crate::application::story::review::resolve_import_review_if_clean(
        &tx,
        story_id,
        &post_mutation_blockers,
    )?;
    let import_state = crate::application::story::review::read_import_state(&tx, story_id, scope)?;

    let projected = project_structure(&structure);

    tx.commit()
        .map_err(|e| transport_error(&e, "commit", story_id))?;

    Ok((
        StructureWriteOutputDto {
            id: story_id.to_string(),
            updated_at: now_iso,
            content_checksum: new_checksum,
            structure_json: new_json,
            structure: projected,
            import_state: import_state.map(|s| s.wire_tag().to_string()),
        },
        extra,
    ))
}

// ---------------------------------------------------------------------------
// Services
// ---------------------------------------------------------------------------

/// Append a new EMPTY node at the end of the display order. When `link_from`
/// is provided, the referenced option of the referenced node is atomically
/// linked to the new node IN THE SAME transaction — the "create and link"
/// gesture never leaves an intermediate half-state.
pub fn add_node(
    db: &mut DbHandle,
    story_id: &str,
    link_from: Option<(&str, usize)>,
) -> Result<StructureWriteOutputDto, AppError> {
    let story = story_id.to_string();
    let link_from = link_from.map(|(node_id, index)| (node_id.to_string(), index));
    apply_structure_mutation(db, story_id, move |structure, _tx| {
        let new_id = next_free_node_id(structure);
        structure.nodes.push(CanonicalNode {
            id: new_id.clone(),
            text: String::new(),
            label: String::new(),
            image_asset_id: None,
            audio_asset_id: None,
            options: Vec::new(),
        });
        if let Some((source_node_id, option_index)) = link_from {
            let source = structure
                .nodes
                .iter_mut()
                .find(|n| n.id == source_node_id)
                .ok_or_else(|| node_missing(&story, &source_node_id))?;
            let option = source
                .options
                .get_mut(option_index)
                .ok_or_else(|| option_index_invalid(&story, &source_node_id, option_index))?;
            option.target = Some(new_id);
        }
        Ok(())
    })
    .map(|(out, ())| out)
}

/// Media assets of a deleted node, captured in-transaction for the
/// post-commit refcounted file GC.
type RemovedAssets = Vec<(String, String)>;

/// Delete a node from the graph. REFUSES the start node (the entry point must
/// exist). The node's media assets are deleted (rows in-transaction, files
/// GC'd post-commit when unreferenced) and ITS recovery buffer entry is
/// purged CONDITIONALLY (`story_id` AND `node_id` — the single per-story
/// draft row may belong to ANOTHER node still being edited; an unconditional
/// purge would silently lose that buffer, NFR8). Options on OTHER nodes that
/// pointed at the deleted node KEEP their target and become `destination à
/// corriger` — visible and repairable, never silently unlinked.
pub fn delete_node(
    db: &mut DbHandle,
    app_data_dir: &Path,
    story_id: &str,
    node_id: &str,
) -> Result<StructureWriteOutputDto, AppError> {
    let story = story_id.to_string();
    let node = node_id.to_string();
    let (out, removed_assets) = apply_structure_mutation(db, story_id, move |structure, tx| {
        if structure.start_node_id == node {
            return Err(delete_start_refused(&story));
        }
        let idx = structure
            .nodes
            .iter()
            .position(|n| n.id == node)
            .ok_or_else(|| node_missing(&story, &node))?;
        let removed = structure.nodes.remove(idx);

        // Reclaim the node's asset rows inside the transaction; the files are
        // GC'd AFTER commit (refcounted by content hash), mirroring
        // `remove_node_media`.
        let mut removed_assets: RemovedAssets = Vec::new();
        for asset_id in removed
            .image_asset_id
            .iter()
            .chain(removed.audio_asset_id.iter())
        {
            let info: Option<(String, String)> = tx
                .query_row(
                    "SELECT content_hash, file_name FROM assets WHERE id = ?1 AND story_id = ?2",
                    rusqlite::params![asset_id, story],
                    |r| Ok((r.get(0)?, r.get(1)?)),
                )
                .optional()
                .map_err(|e| transport_error(&e, "read_assets", &story))?;
            tx.execute(
                "DELETE FROM assets WHERE id = ?1 AND story_id = ?2",
                rusqlite::params![asset_id, story],
            )
            .map_err(|e| transport_error(&e, "delete_assets", &story))?;
            if let Some(info) = info {
                removed_assets.push(info);
            }
        }

        // Purge the recovery buffer FOR THIS NODE ONLY. The table's PK is
        // `story_id` (one draft per story), so the row may buffer another
        // node's unsaved content — the WHERE node_id clause protects it.
        tx.execute(
            "DELETE FROM node_drafts WHERE story_id = ?1 AND node_id = ?2",
            rusqlite::params![story, node],
        )
        .map_err(|e| transport_error(&e, "delete_node_draft", &story))?;

        Ok(removed_assets)
    })?;

    // Post-commit, best-effort refcounted file GC (same helper as the media
    // removal path).
    let media_dir = crate::infrastructure::filesystem::resolve_node_media_dir(app_data_dir);
    for info in removed_assets {
        crate::application::story::node::gc_unreferenced_media_file(db, &media_dir, Some(info));
    }

    Ok(out)
}

/// Swap a node with its neighbor in the DISPLAY order. The start node is
/// designated by `startNodeId`, NOT by position 0 — moving it is legitimate.
/// A move with no room (already first / last) is an acknowledged no-op: the
/// graph is rewritten identical, never refused (a stale double-click must not
/// surface an error).
pub fn move_node(
    db: &mut DbHandle,
    story_id: &str,
    node_id: &str,
    direction: MoveDirection,
) -> Result<StructureWriteOutputDto, AppError> {
    let story = story_id.to_string();
    let node = node_id.to_string();
    apply_structure_mutation(db, story_id, move |structure, _tx| {
        let idx = structure
            .nodes
            .iter()
            .position(|n| n.id == node)
            .ok_or_else(|| node_missing(&story, &node))?;
        match direction {
            MoveDirection::Up if idx > 0 => structure.nodes.swap(idx, idx - 1),
            MoveDirection::Down if idx + 1 < structure.nodes.len() => {
                structure.nodes.swap(idx, idx + 1)
            }
            _ => {}
        }
        Ok(())
    })
    .map(|(out, ())| out)
}

/// Add an option `{label, target: None}` to a node. The label is typed at
/// creation and bounded by the same cap as the node metadata label.
pub fn add_option(
    db: &mut DbHandle,
    story_id: &str,
    node_id: &str,
    label: &str,
) -> Result<StructureWriteOutputDto, AppError> {
    if label.chars().count() > MAX_NODE_LABEL_CHARS {
        return Err(AppError::local_storage_unavailable(
            "Ajout impossible: libellé d'option trop long.",
            "Réduis la taille du libellé puis réessaie.",
        )
        .with_details(serde_json::json!({ "source": "option_label_too_long" })));
    }
    let story = story_id.to_string();
    let node = node_id.to_string();
    let label = label.to_string();
    apply_structure_mutation(db, story_id, move |structure, _tx| {
        let target_node = structure
            .nodes
            .iter_mut()
            .find(|n| n.id == node)
            .ok_or_else(|| node_missing(&story, &node))?;
        target_node.options.push(CanonicalOption {
            label,
            target: None,
        });
        Ok(())
    })
    .map(|(out, ())| out)
}

/// Set an option's destination. `Some(target)`: REFUSED unless the target
/// node exists in the graph — an invalid link is PREVENTED at write time
/// (AC2), never persisted; self-reference is a legitimate narrative loop and
/// is allowed. `None`: unlink (back to `non liée`).
pub fn set_option_link(
    db: &mut DbHandle,
    story_id: &str,
    node_id: &str,
    option_index: usize,
    target: Option<&str>,
) -> Result<StructureWriteOutputDto, AppError> {
    let story = story_id.to_string();
    let node = node_id.to_string();
    let target = target.map(str::to_string);
    apply_structure_mutation(db, story_id, move |structure, _tx| {
        if let Some(target_id) = target.as_deref() {
            let exists = structure.nodes.iter().any(|n| n.id == target_id);
            if !exists {
                return Err(link_target_missing(&story, target_id));
            }
        }
        let source = structure
            .nodes
            .iter_mut()
            .find(|n| n.id == node)
            .ok_or_else(|| node_missing(&story, &node))?;
        let option = source
            .options
            .get_mut(option_index)
            .ok_or_else(|| option_index_invalid(&story, &node, option_index))?;
        option.target = target;
        Ok(())
    })
    .map(|(out, ())| out)
}

/// Remove an option from a node (an out-of-range index is a typed refusal).
pub fn remove_option(
    db: &mut DbHandle,
    story_id: &str,
    node_id: &str,
    option_index: usize,
) -> Result<StructureWriteOutputDto, AppError> {
    let story = story_id.to_string();
    let node = node_id.to_string();
    apply_structure_mutation(db, story_id, move |structure, _tx| {
        let source = structure
            .nodes
            .iter_mut()
            .find(|n| n.id == node)
            .ok_or_else(|| node_missing(&story, &node))?;
        if option_index >= source.options.len() {
            return Err(option_index_invalid(&story, &node, option_index));
        }
        source.options.remove(option_index);
        Ok(())
    })
    .map(|(out, ())| out)
}

// ---------------------------------------------------------------------------
// Error mapping (PII-safe: ids and closed stages only, never user content)
// ---------------------------------------------------------------------------

fn story_missing(story_id: &str) -> AppError {
    AppError::library_inconsistent(
        "Histoire introuvable, recharge la bibliothèque.",
        "Retourne à la bibliothèque et recharge la liste.",
    )
    .with_details(serde_json::json!({ "source": "story_missing", "id": story_id }))
}

fn structure_corrupt(story_id: &str) -> AppError {
    AppError::library_inconsistent(
        "La structure interne de l'histoire est illisible ou incohérente.",
        "Relance Rustory pour reconstruire la vue cohérente.",
    )
    .with_details(serde_json::json!({ "source": "structure_corrupt", "id": story_id }))
}

fn node_missing(story_id: &str, node_id: &str) -> AppError {
    AppError::library_inconsistent(
        "Le nœud à modifier est introuvable dans l'histoire.",
        "Recharge l'éditeur puis réessaie.",
    )
    .with_details(
        serde_json::json!({ "source": "node_missing", "id": story_id, "nodeId": node_id }),
    )
}

/// Refusal of a structural write on a story outside the FULL edit scope
/// (same cause as the node content guard — a device-pack story's structure
/// is carried by the pack; dedicated source marker for support triage).
fn structure_not_editable(story_id: &str) -> AppError {
    AppError::library_inconsistent(
        "Le contenu de cette histoire est porté par le pack copié depuis l'appareil et ne peut pas être modifié ici.",
        "Tu peux modifier le titre depuis l'éditeur ; le contenu du pack reste celui de l'appareil.",
    )
    .with_details(serde_json::json!({ "source": "structure_not_editable", "id": story_id }))
}

/// Deleting the start node is refused: the story must keep its entry point.
fn delete_start_refused(story_id: &str) -> AppError {
    AppError::library_inconsistent(
        "Le nœud de départ ne peut pas être supprimé.",
        "Choisis un autre nœud à supprimer.",
    )
    .with_details(serde_json::json!({ "source": "delete_start_refused", "id": story_id }))
}

/// Linking toward a node absent from the graph is PREVENTED (AC2): the
/// invalid link is never written.
fn link_target_missing(story_id: &str, target_id: &str) -> AppError {
    AppError::library_inconsistent(
        "La destination choisie n'existe plus dans l'histoire.",
        "Recharge l'éditeur puis choisis un nœud existant.",
    )
    .with_details(serde_json::json!({
        "source": "link_target_missing",
        "id": story_id,
        "targetId": target_id,
    }))
}

/// The referenced option index does not exist on the node (stale UI state).
fn option_index_invalid(story_id: &str, node_id: &str, option_index: usize) -> AppError {
    AppError::library_inconsistent(
        "L'option à modifier est introuvable dans ce nœud.",
        "Recharge l'éditeur puis réessaie.",
    )
    .with_details(serde_json::json!({
        "source": "option_index_invalid",
        "id": story_id,
        "nodeId": node_id,
        "optionIndex": option_index,
    }))
}

fn transport_error(_err: &rusqlite::Error, stage: &'static str, story_id: &str) -> AppError {
    AppError::local_storage_unavailable(
        "Rustory n'a pas pu enregistrer ta modification.",
        "Réessaie dans un instant ; si le problème persiste, consulte les traces locales.",
    )
    .with_details(serde_json::json!({
        "source": "sqlite_structure_write",
        "stage": stage,
        "id": story_id,
    }))
}

/// `true` when the canonical facts carry at least one BLOCKING blocker. A
/// fixable-only set (an invalid persisted title, a broken option link) never
/// blocks a structural write — repairing IS a structural write.
fn has_blocking(facts: &CanonicalStoryFacts) -> bool {
    validate_canonical(facts)
        .iter()
        .any(|b| b.severity == Severity::Blocking)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::application::story::{create_story, get_story_detail, CreateStoryInput};
    use crate::domain::shared::AppErrorCode;
    use crate::infrastructure::db;

    fn fresh_db() -> DbHandle {
        let mut handle = db::open_in_memory().expect("open in-memory db");
        db::run_migrations(&mut handle).expect("migrate");
        handle
    }

    fn seeded_story(db: &mut DbHandle) -> String {
        create_story(
            db,
            CreateStoryInput {
                title: "Structure".into(),
            },
        )
        .expect("create")
        .id
    }

    fn stored_structure(db: &DbHandle, story_id: &str) -> (u32, CanonicalStructure, String) {
        let (schema_version, json, checksum): (u32, String, String) = db
            .conn()
            .query_row(
                "SELECT schema_version, structure_json, content_checksum FROM stories WHERE id = ?1",
                rusqlite::params![story_id],
                |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
            )
            .expect("row");
        let structure: CanonicalStructure = serde_json::from_str(&json).expect("parse v3");
        assert_eq!(
            checksum,
            content_checksum(&json),
            "stored checksum must always match the stored bytes"
        );
        (schema_version, structure, checksum)
    }

    fn mark_local_import(db: &DbHandle, story_id: &str) {
        db.conn()
            .execute(
                "INSERT INTO story_local_imports (story_id, source_format, source_format_version, source_name, artifact_checksum, import_state, findings_summary, imported_at) \
                 VALUES (?1, 'rustory', 1, 'a.rustory', ?2, 'recognized', NULL, '2026-07-04T00:00:00.000Z')",
                rusqlite::params![story_id, "a".repeat(64)],
            )
            .expect("mark imported");
    }

    fn mark_device_pack(db: &DbHandle, story_id: &str) {
        db.conn()
            .execute(
                "INSERT INTO story_imports (story_id, pack_uuid, source_device_identifier, imported_at, pack_file_count, pack_total_bytes, pack_checksum, source_family) \
                 VALUES (?1, '019739b2-0000-7000-8000-000000000000', '0123456789abcdef0123456789abcdef', '2026-07-06T00:00:00.000Z', 5, 18, ?2, 'lunii')",
                rusqlite::params![story_id, "ab".repeat(32)],
            )
            .expect("insert pack provenance");
    }

    // ---------------- add_node ----------------

    #[test]
    fn add_node_appends_an_empty_node_with_the_smallest_free_id() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);

        let out = add_node(&mut db, &story_id, None).expect("add");
        assert_eq!(out.structure.nodes.len(), 2);
        assert_eq!(out.structure.nodes[1].id, "n2");
        assert!(!out.structure.nodes[1].is_start);
        assert!(out.structure.nodes[1].options.is_empty());

        let (_, structure, _) = stored_structure(&db, &story_id);
        assert_eq!(structure.nodes.len(), 2);
        assert_eq!(structure.nodes[1].id, "n2");
        assert_eq!(structure.start_node_id, "n1");
    }

    #[test]
    fn add_node_ids_fill_the_smallest_gap() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");
        add_node(&mut db, &story_id, None).expect("n3");
        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2").expect("del n2");

        let out = add_node(&mut db, &story_id, None).expect("re-add");
        let ids: Vec<&str> = out.structure.nodes.iter().map(|n| n.id.as_str()).collect();
        assert!(ids.contains(&"n2"), "the freed id n2 is reused: {ids:?}");
    }

    #[test]
    fn add_node_never_recycles_an_id_still_referenced_by_a_broken_link() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Aller").expect("option");
        add_node(&mut db, &story_id, Some(("n1", 0))).expect("create-and-link n2");
        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2")
            .expect("delete the referenced n2 (link kept, flagged)");

        // The freed id "n2" is STILL referenced by the à-corriger option:
        // recycling it would silently turn the flagged trace into a live
        // link toward an unrelated node.
        let out = add_node(&mut db, &story_id, None).expect("re-add");
        let new_id = out
            .structure
            .nodes
            .iter()
            .map(|n| n.id.as_str())
            .find(|id| *id != "n1")
            .expect("a second node exists");
        assert_eq!(new_id, "n3", "the ghost-referenced id n2 must be skipped");
        assert_eq!(
            out.structure.nodes[0].options[0].state, "broken",
            "the flagged trace stays broken, never silently re-linked"
        );
        assert_eq!(
            out.structure.nodes[0].options[0].target.as_deref(),
            Some("n2"),
            "the preserved target still names the deleted node"
        );
    }

    #[test]
    fn add_node_with_link_from_links_atomically() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Continuer").expect("option");

        let out = add_node(&mut db, &story_id, Some(("n1", 0))).expect("create-and-link");
        let start = &out.structure.nodes[0];
        assert_eq!(start.options[0].target.as_deref(), Some("n2"));
        assert_eq!(start.options[0].state, "linked");
        assert!(!start.has_issue);

        let (_, structure, _) = stored_structure(&db, &story_id);
        assert_eq!(structure.nodes[0].options[0].target.as_deref(), Some("n2"));
    }

    #[test]
    fn add_node_with_invalid_link_from_rolls_back_everything() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);

        // No option exists at index 0 — the whole mutation (including the node
        // append) must roll back: never a half-state (node created, link lost).
        let err = add_node(&mut db, &story_id, Some(("n1", 0))).expect_err("must refuse");
        assert_eq!(err.code, AppErrorCode::LibraryInconsistent);
        let details = err.details.as_ref().expect("details");
        assert_eq!(details["source"], "option_index_invalid");

        let (_, structure, _) = stored_structure(&db, &story_id);
        assert_eq!(structure.nodes.len(), 1, "the appended node rolled back");
    }

    // ---------------- delete_node ----------------

    #[test]
    fn delete_node_refuses_the_start_node() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        let err = delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n1")
            .expect_err("must refuse the start node");
        let details = err.details.as_ref().expect("details");
        assert_eq!(details["source"], "delete_start_refused");
    }

    #[test]
    fn delete_node_keeps_pointing_options_as_broken_links() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Aller").expect("option");
        add_node(&mut db, &story_id, Some(("n1", 0))).expect("create-and-link n2");

        let out = delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2")
            .expect("delete a REFERENCED node must stay possible");
        let start = &out.structure.nodes[0];
        // The trace survives: the option keeps its target, flagged broken.
        assert_eq!(start.options[0].target.as_deref(), Some("n2"));
        assert_eq!(start.options[0].state, "broken");
        assert!(start.has_issue, "the issue is localized on the node");

        // Persisted facts agree (a Fixable broken link, no Blocking).
        let (_, structure, _) = stored_structure(&db, &story_id);
        assert_eq!(structure.nodes.len(), 1);
        assert_eq!(structure.nodes[0].options[0].target.as_deref(), Some("n2"));
    }

    #[test]
    fn delete_node_purges_only_that_nodes_draft() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");

        // The single per-story draft row buffers UNSAVED content of n1 — the
        // node being deleted is n2, so the buffer must survive.
        db.conn()
            .execute(
                "INSERT INTO node_drafts (story_id, node_id, draft_text, draft_label, draft_at) \
                 VALUES (?1, 'n1', 'texte non sauvé', '', '2026-07-04T00:00:00.000Z')",
                rusqlite::params![story_id],
            )
            .expect("seed draft");

        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2").expect("delete n2");
        let survived: u32 = db
            .conn()
            .query_row(
                "SELECT COUNT(*) FROM node_drafts WHERE story_id = ?1 AND node_id = 'n1'",
                rusqlite::params![story_id],
                |r| r.get(0),
            )
            .expect("count");
        assert_eq!(survived, 1, "another node's unsaved buffer must survive");

        // Now buffer n2's sibling — deleting the BUFFERED node purges it.
        add_node(&mut db, &story_id, None).expect("n2 again");
        db.conn()
            .execute(
                "UPDATE node_drafts SET node_id = 'n2' WHERE story_id = ?1",
                rusqlite::params![story_id],
            )
            .expect("retarget draft");
        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2").expect("delete");
        let remaining: u32 = db
            .conn()
            .query_row(
                "SELECT COUNT(*) FROM node_drafts WHERE story_id = ?1",
                rusqlite::params![story_id],
                |r| r.get(0),
            )
            .expect("count");
        assert_eq!(remaining, 0, "the deleted node's buffer is purged");
    }

    #[test]
    fn delete_node_reclaims_asset_rows_and_files() {
        let mut db = fresh_db();
        let tmp = tempfile::TempDir::new().expect("tmp");
        let app_data_dir = tmp.path();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");

        // Attach a real (decodable) image through the actual store path —
        // the store transcodes images, so a magic-only header is refused.
        let png: Vec<u8> = {
            let img = image::RgbaImage::from_pixel(16, 12, image::Rgba([9, 9, 9, 255]));
            let mut out = Vec::new();
            image::DynamicImage::ImageRgba8(img)
                .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
                .expect("encode png");
            out
        };
        crate::application::story::node::attach_node_media(
            &mut db,
            app_data_dir,
            crate::application::story::node::AttachNodeMediaInput {
                story_id: story_id.clone(),
                node_id: "n2".into(),
                kind: crate::infrastructure::filesystem::MediaKind::Image,
                bytes: png,
            },
        )
        .expect("attach");

        let (asset_count_before, file_name): (u32, String) = {
            let count: u32 = db
                .conn()
                .query_row(
                    "SELECT COUNT(*) FROM assets WHERE story_id = ?1",
                    rusqlite::params![story_id],
                    |r| r.get(0),
                )
                .expect("count");
            let name: String = db
                .conn()
                .query_row(
                    "SELECT file_name FROM assets WHERE story_id = ?1",
                    rusqlite::params![story_id],
                    |r| r.get(0),
                )
                .expect("name");
            (count, name)
        };
        assert_eq!(asset_count_before, 1);
        let media_dir = crate::infrastructure::filesystem::resolve_node_media_dir(app_data_dir);
        assert!(media_dir.join(&file_name).is_file(), "file promoted");

        delete_node(&mut db, app_data_dir, &story_id, "n2").expect("delete");

        let asset_count_after: u32 = db
            .conn()
            .query_row(
                "SELECT COUNT(*) FROM assets WHERE story_id = ?1",
                rusqlite::params![story_id],
                |r| r.get(0),
            )
            .expect("count");
        assert_eq!(asset_count_after, 0, "asset rows reclaimed");
        assert!(
            !media_dir.join(&file_name).is_file(),
            "unreferenced file GC'd post-commit"
        );
    }

    // ---------------- move_node ----------------

    #[test]
    fn move_node_swaps_display_order_and_start_may_move() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");

        // Move the START node down: display order changes, startNodeId stays.
        let out = move_node(&mut db, &story_id, "n1", MoveDirection::Down).expect("move");
        let ids: Vec<&str> = out.structure.nodes.iter().map(|n| n.id.as_str()).collect();
        assert_eq!(ids, vec!["n2", "n1"]);
        assert_eq!(out.structure.start_node_id, "n1");
        assert!(out.structure.nodes[1].is_start, "start follows its node");

        // No room: moving the first node up is an acknowledged no-op.
        let out = move_node(&mut db, &story_id, "n2", MoveDirection::Up).expect("no-op");
        let ids: Vec<&str> = out.structure.nodes.iter().map(|n| n.id.as_str()).collect();
        assert_eq!(ids, vec!["n2", "n1"]);
    }

    #[test]
    fn a_no_room_move_never_rewrites_the_row() {
        // A stale double-click on `Monter` at the top must not bump
        // `updated_at` (a persisted, exported, user-visible metadata) nor
        // recompute anything: the ACK is built from the state read in the
        // transaction, without an UPDATE.
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");
        let (updated_before, checksum_before): (String, String) = db
            .conn()
            .query_row(
                "SELECT updated_at, content_checksum FROM stories WHERE id = ?1",
                rusqlite::params![story_id],
                |r| Ok((r.get(0)?, r.get(1)?)),
            )
            .expect("row");

        std::thread::sleep(std::time::Duration::from_millis(2));
        let out = move_node(&mut db, &story_id, "n1", MoveDirection::Up).expect("no-op move");

        let (updated_after, checksum_after): (String, String) = db
            .conn()
            .query_row(
                "SELECT updated_at, content_checksum FROM stories WHERE id = ?1",
                rusqlite::params![story_id],
                |r| Ok((r.get(0)?, r.get(1)?)),
            )
            .expect("row");
        assert_eq!(
            updated_after, updated_before,
            "a no-op move must not bump updated_at"
        );
        assert_eq!(checksum_after, checksum_before);
        // The ACK mirrors the STORED state, not a fresh timestamp.
        assert_eq!(out.updated_at, updated_before);
        assert_eq!(out.content_checksum, checksum_before);
    }

    #[test]
    fn a_blocking_issue_degrades_structure_and_node_together() {
        // The producer-side lock of the cross-boundary invariant the TS guard
        // enforces: on a BLOCKING canonical issue `get_story_detail` degrades
        // BOTH projections — never one null without the other.
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        db.conn()
            .execute(
                "UPDATE stories SET content_checksum = ?1 WHERE id = ?2",
                rusqlite::params!["0".repeat(64), story_id],
            )
            .expect("corrupt the checksum");

        let detail = get_story_detail(&db, &std::env::temp_dir(), &story_id, None)
            .expect("ok")
            .expect("some");
        assert!(detail.structure.is_none(), "structure degrades on Blocking");
        assert!(detail.node.is_none(), "node degrades WITH the structure");
    }

    // ---------------- add_option / set_option_link / remove_option ----------

    #[test]
    fn add_option_appends_an_unlinked_option() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        let out = add_option(&mut db, &story_id, "n1", "Continuer").expect("add option");
        let start = &out.structure.nodes[0];
        assert_eq!(start.options.len(), 1);
        assert_eq!(start.options[0].label, "Continuer");
        assert!(start.options[0].target.is_none());
        assert_eq!(start.options[0].state, "unlinked");
        assert!(!start.has_issue, "unlinked is a NORMAL state, no issue");
    }

    #[test]
    fn add_option_refuses_an_oversize_label() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        let long = "a".repeat(MAX_NODE_LABEL_CHARS + 1);
        let err = add_option(&mut db, &story_id, "n1", &long).expect_err("must refuse");
        let details = err.details.as_ref().expect("details");
        assert_eq!(details["source"], "option_label_too_long");
    }

    #[test]
    fn set_option_link_links_unlinks_and_allows_self_reference() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Choix").expect("option");
        add_node(&mut db, &story_id, None).expect("n2");

        let out = set_option_link(&mut db, &story_id, "n1", 0, Some("n2")).expect("link");
        assert_eq!(out.structure.nodes[0].options[0].state, "linked");

        // Self-reference: a legitimate narrative loop.
        let out = set_option_link(&mut db, &story_id, "n1", 0, Some("n1")).expect("self-link");
        assert_eq!(out.structure.nodes[0].options[0].state, "linked");
        assert_eq!(
            out.structure.nodes[0].options[0].target.as_deref(),
            Some("n1")
        );

        let out = set_option_link(&mut db, &story_id, "n1", 0, None).expect("unlink");
        assert_eq!(out.structure.nodes[0].options[0].state, "unlinked");
        assert!(out.structure.nodes[0].options[0].target.is_none());
    }

    #[test]
    fn set_option_link_prevents_a_missing_destination() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Choix").expect("option");

        let err =
            set_option_link(&mut db, &story_id, "n1", 0, Some("ghost")).expect_err("must refuse");
        assert_eq!(err.code, AppErrorCode::LibraryInconsistent);
        let details = err.details.as_ref().expect("details");
        assert_eq!(details["source"], "link_target_missing");

        // Nothing was written: the option is still unlinked.
        let (_, structure, _) = stored_structure(&db, &story_id);
        assert!(structure.nodes[0].options[0].target.is_none());
    }

    #[test]
    fn remove_option_drops_it_and_refuses_stale_indexes() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Un").expect("option");
        add_option(&mut db, &story_id, "n1", "Deux").expect("option");

        let out = remove_option(&mut db, &story_id, "n1", 0).expect("remove");
        assert_eq!(out.structure.nodes[0].options.len(), 1);
        assert_eq!(out.structure.nodes[0].options[0].label, "Deux");

        let err = remove_option(&mut db, &story_id, "n1", 5).expect_err("stale index");
        let details = err.details.as_ref().expect("details");
        assert_eq!(details["source"], "option_index_invalid");
    }

    // ---------------- FR18/FR21: fail-closed edit scope on EVERY service ----

    #[test]
    fn every_structural_service_refuses_a_device_pack_story() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Choix").expect("pre-pack option");
        add_node(&mut db, &story_id, None).expect("pre-pack n2");
        mark_device_pack(&db, &story_id);

        let tmp = tempfile::TempDir::new().expect("tmp");
        let failures: Vec<(&str, AppError)> = vec![
            (
                "add_node",
                add_node(&mut db, &story_id, None).expect_err("add_node"),
            ),
            (
                "delete_node",
                delete_node(&mut db, tmp.path(), &story_id, "n2").expect_err("delete_node"),
            ),
            (
                "move_node",
                move_node(&mut db, &story_id, "n2", MoveDirection::Up).expect_err("move_node"),
            ),
            (
                "add_option",
                add_option(&mut db, &story_id, "n1", "X").expect_err("add_option"),
            ),
            (
                "set_option_link",
                set_option_link(&mut db, &story_id, "n1", 0, Some("n2"))
                    .expect_err("set_option_link"),
            ),
            (
                "remove_option",
                remove_option(&mut db, &story_id, "n1", 0).expect_err("remove_option"),
            ),
        ];
        for (service, err) in failures {
            assert_eq!(
                err.code,
                AppErrorCode::LibraryInconsistent,
                "{service} must refuse a device-pack story"
            );
            let details = err.details.as_ref().expect("details");
            assert_eq!(
                details["source"], "structure_not_editable",
                "{service} must use the authoritative guard"
            );
            assert_eq!(
                err.message,
                "Le contenu de cette histoire est porté par le pack copié depuis l'appareil et ne peut pas être modifié ici.",
                "{service} must carry the revised pack message (no version promise)"
            );
        }
    }

    // FR21: a `.rustory` import carries the FULL edit scope — structural
    // mutations go through exactly like a native story's.
    #[test]
    fn a_rustory_import_accepts_structural_mutations() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        mark_local_import(&db, &story_id);

        let out = add_node(&mut db, &story_id, None)
            .expect("a .rustory import reorganizes like a native story");
        assert_eq!(out.structure.nodes.len(), 2);
        let (_, structure, _) = stored_structure(&db, &story_id);
        assert_eq!(structure.nodes.len(), 2, "the mutation is persisted");
    }

    fn mark_needs_review(db: &DbHandle, story_id: &str) {
        db.conn()
            .execute(
                "INSERT INTO story_local_imports (story_id, source_format, source_format_version, source_name, artifact_checksum, import_state, findings_summary, imported_at) \
                 VALUES (?1, 'rustory', 1, 'a.rustory', ?2, 'needs_review', '[{\"aspect\":\"structure\",\"category\":\"ambiguous\"}]', '2026-07-06T00:00:00.000Z')",
                rusqlite::params![story_id, "a".repeat(64)],
            )
            .expect("mark needs_review");
    }

    fn import_state_of(db: &DbHandle, story_id: &str) -> String {
        db.conn()
            .query_row(
                "SELECT import_state FROM story_local_imports WHERE story_id = ?1",
                rusqlite::params![story_id],
                |r| r.get(0),
            )
            .expect("provenance row")
    }

    // AC3 signature path: repairing the broken link IS what settles the
    // review — the structural write that leaves the graph fully sound flips
    // the durable state and the ACK carries it.
    #[test]
    fn repairing_a_broken_link_resolves_a_pending_review() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Aller").expect("option");
        add_node(&mut db, &story_id, Some(("n1", 0))).expect("create-and-link n2");
        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2")
            .expect("break the link");
        mark_needs_review(&db, &story_id);

        // Add a fresh node then repair the option toward it: the graph is
        // sound again and the review settles.
        add_node(&mut db, &story_id, None).expect("n3");
        assert_eq!(
            import_state_of(&db, &story_id),
            "needs_review",
            "adding a node while the link is still broken must NOT resolve"
        );

        let out = set_option_link(&mut db, &story_id, "n1", 0, Some("n3")).expect("repair");
        assert_eq!(out.import_state.as_deref(), Some("resolved"));
        assert_eq!(import_state_of(&db, &story_id), "resolved");
    }

    // An acknowledged no-op (same canonical bytes) is NOT a real write: the
    // pending review stays, but the ACK still carries the current state.
    #[test]
    fn a_no_op_move_does_not_resolve_but_acks_the_current_state() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");
        mark_needs_review(&db, &story_id);

        // Moving the first node up has no room: acknowledged without UPDATE.
        let out = move_node(&mut db, &story_id, "n1", MoveDirection::Up).expect("no-op");
        assert_eq!(
            out.import_state.as_deref(),
            Some("needsReview"),
            "the no-op ACK carries the CURRENT state"
        );
        assert_eq!(
            import_state_of(&db, &story_id),
            "needs_review",
            "no real write happened, the review stays pending"
        );
    }

    #[test]
    fn structural_writes_never_touch_another_story() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        let other_id = create_story(
            &mut db,
            CreateStoryInput {
                title: "Autre".into(),
            },
        )
        .expect("other")
        .id;
        let (_, _, other_checksum_before) = stored_structure(&db, &other_id);

        add_node(&mut db, &story_id, None).expect("mutate first story");

        let (_, _, other_checksum_after) = stored_structure(&db, &other_id);
        assert_eq!(
            other_checksum_before, other_checksum_after,
            "FR18: another story's canonical row is never touched"
        );
    }

    // ---------------- projection sanity through get_story_detail ------------

    #[test]
    fn structure_projection_flows_through_get_story_detail() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Aller").expect("option");
        add_node(&mut db, &story_id, Some(("n1", 0))).expect("n2");

        let detail = get_story_detail(&db, &std::env::temp_dir(), &story_id, None)
            .expect("ok")
            .expect("some");
        let structure = detail.structure.expect("structure projected");
        assert_eq!(structure.start_node_id, "n1");
        assert_eq!(structure.nodes.len(), 2);
        let node = detail.node.expect("node projected");
        assert_eq!(node.id, "n1", "default selection is the start node");

        // Targeted read: the second node's content.
        let detail = get_story_detail(&db, &std::env::temp_dir(), &story_id, Some("n2"))
            .expect("ok")
            .expect("some");
        assert_eq!(detail.node.expect("node").id, "n2");

        // Stale selection over a HEALTHY graph: graceful fallback to start.
        let detail = get_story_detail(&db, &std::env::temp_dir(), &story_id, Some("ghost"))
            .expect("ok")
            .expect("some");
        assert!(detail.structure.is_some(), "healthy graph stays projected");
        assert_eq!(detail.node.expect("node").id, "n1", "fallback = start");
    }

    #[test]
    fn a_non_start_nodes_draft_stays_recoverable_through_the_targeted_projection() {
        // NFR8 in multi-node: the recovery read compares the buffered draft
        // against the node TARGETED by `draft.node_id`. Through the untargeted
        // (start-node) projection this comparison silently died for every
        // other node — this locks the corrected path, replaying the command's
        // exact predicate.
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_node(&mut db, &story_id, None).expect("n2");
        crate::application::story::node::save_node_content(
            &mut db,
            &std::env::temp_dir(),
            crate::application::story::node::SaveNodeContentInput {
                story_id: story_id.clone(),
                node_id: "n2".into(),
                text: "persisté".into(),
                label: String::new(),
            },
        )
        .expect("persist n2 content");
        // A crash left a fresher buffered value for n2.
        db.conn()
            .execute(
                "INSERT INTO node_drafts (story_id, node_id, draft_text, draft_label, draft_at) \
                 VALUES (?1, 'n2', 'tapé mais pas sauvé', '', '2026-07-04T00:00:00.000Z')",
                rusqlite::params![story_id],
            )
            .expect("seed draft");

        let draft_node_id = "n2";
        let persisted =
            get_story_detail(&db, &std::env::temp_dir(), &story_id, Some(draft_node_id))
                .expect("ok")
                .and_then(|d| d.node)
                .filter(|n| n.id == draft_node_id)
                .expect("the targeted projection must find the buffered node");
        assert_eq!(persisted.text, "persisté");
        assert_ne!(
            persisted.text, "tapé mais pas sauvé",
            "the differing draft is exactly what recovery must surface"
        );
    }

    #[test]
    fn broken_link_keeps_structure_and_node_projected() {
        let mut db = fresh_db();
        let story_id = seeded_story(&mut db);
        add_option(&mut db, &story_id, "n1", "Aller").expect("option");
        add_node(&mut db, &story_id, Some(("n1", 0))).expect("n2");
        delete_node(&mut db, std::env::temp_dir().as_path(), &story_id, "n2").expect("delete");

        // A Fixable broken link must NOT unmount the projection: the user has
        // to SEE the flagged spot to repair it.
        let detail = get_story_detail(&db, &std::env::temp_dir(), &story_id, None)
            .expect("ok")
            .expect("some");
        let structure = detail.structure.expect("structure stays projected");
        assert!(structure.nodes[0].has_issue);
        assert_eq!(structure.nodes[0].options[0].state, "broken");
        assert!(detail.node.is_some(), "node stays projected too");
    }
}
